"""The shipped set phrases (app/phrase_data.py, generated by scripts/build_phrase_data.py from JMdict).

The table is read by the analyzer, the token store and the cards, so it must decode, hold what its header says, and
keep every phrase in the shape the matcher reads. And it is keyed by how the app's own tokenizer reads each phrase: a
tokenizer or join-table change that reads a phrase differently, without a rebuild, would leave a phrase no text can
match — the drift guard below reads real phrases again and fails first. The attribution JMdict's licence asks for
ships with the data.
"""

import pytest

from app import analyzer, phrase_data, phrases, settings_manager

# Real phrases of the table, by the spelling it shows them in — idioms, a phrase ending in grammar, one with a light
# verb, one whose word lives only inside it.
SAMPLE = ("気がする", "腑に落ちる", "もしかしたら", "首を傾げる", "気がつく", "本題に入る", "眉根を寄せる", "歯を食いしばる",
          "手っ取り早い", "かけがえのない", "間違いない", "申し訳ない", "気をつける", "耳を傾ける", "あっという間",
          "お帰りなさい", "お気に入り", "興味を持つ", "途方に暮れる", "目を向ける")


@pytest.fixture(scope="module")
def rows():
    return phrase_data.phrases()


def test_the_table_decodes_and_holds_what_its_header_says(rows):
    assert len(rows) == phrase_data.COUNT > 10_000
    assert phrase_data.REVISION and phrase_data.JMDICT_CREATED


def test_every_phrase_is_two_to_five_words_in_the_matchers_shape(rows):
    """Lemmas and readings `|`-joined, one role per word, a spelling and a reading to show, the pre-noun mark; no key
    holds a space or an empty lemma; every phrase has a real word in it."""
    for key, readings, roles, shown, reading, prenoun in rows:
        lemmas = key.split("|")
        assert 2 <= len(lemmas) <= 5 and all(lemmas) and " " not in key, key
        assert len(readings.split("|")) == len(lemmas) == len(roles), key
        assert set(roles) <= set("cblg") and set(roles) & set("cb"), key
        assert shown and reading and prenoun in (0, 1), key
    assert len({row[0] for row in rows}) == len(rows), "one row per phrase"


def test_the_drift_guard_real_phrases_read_to_their_stored_words(rows):
    """Each sample phrase, read alone by today's tokenizer and tables as the build reads it (every parsing switch
    at its default, shared data never reads a library's names), gives the words the table stores for it."""
    by_shown = {row[3]: row for row in rows}
    analyzer.SANITIZE_JA = True
    defaults = settings_manager.DEFAULT_SETTINGS["logic"]
    for name in ("names_katakana", "names_recurring", "names_kanji", "names_work_terms", "phrases_and_titles"):
        analyzer.LOGIC[name] = defaults.get(name, True)
    tagger, joins = analyzer.Tagger(), analyzer.affix_joins()
    for spelling in SAMPLE:
        assert spelling in by_shown, f"{spelling} is no longer shown as a phrase"
        words = [analyzer._sanitize_term(analyzer.word_lemma(w))
                 for w in analyzer.join_affixes(tagger(spelling), joins, library=False)]
        assert "|".join(words) == by_shown[spelling][0], spelling


def test_the_rules_hold_on_the_table(rows):
    """Nothing the tokenizer reads as one word, no one word + grammar, no title (進撃の巨人), and a word that lives
    only inside its phrase marked so (腑 in 腑に落ちる, 手っ取り in 手っ取り早い) while a free one is not (気)."""
    by_shown = {row[3]: row for row in rows}
    keys = {row[0] for row in rows}
    assert "其れ|は" not in keys and "言う|て" not in keys and "何|で" not in keys, "one word + grammar"
    assert "進撃|の|巨人" not in keys, "a title is a name, never a phrase"
    assert "良い|と|思う" not in keys, "most of its matches are two words side by side"
    assert by_shown["腑に落ちる"][2][0] == "b" and by_shown["手っ取り早い"][2][0] == "b"
    assert by_shown["気がする"][2] == "cgl" and by_shown["気がつく"][2][0] == "c"


def test_the_pre_noun_adjectivals_are_jmdicts(rows):
    """The phrases JMdict classes only as pre-noun adjectivals carry the mark — ああいう, こういう, そういう, どういう,
    罪なき — and so do the expressions it sends to one (そういった 'like that', 'see そういう'; こういった): each
    stands only before a noun, so そう言った。 'said so' is no use of そういった. 気がする is none of them."""
    marked = {row[3] for row in rows if row[5]}
    assert {"ああいう", "こういう", "そういう", "どういう", "罪なき", "そう言った", "こういった"} <= marked
    assert "気がする" not in marked and "よく言う" not in marked
    assert 20 <= len(marked) <= 60


def test_the_matcher_reads_the_table(rows):
    """app.phrases builds its set from exactly these rows (and finds a row by its Word)."""
    found_in = phrases.load()
    index = found_in.of_word("気が為る")
    assert found_in.entry(index).display == "気がする" and found_in.entry(index).reading == "キガスル"


def test_the_attribution_ships_with_the_data():
    """JMdict's licence (CC BY-SA 4.0) asks for the EDRDG's acknowledgement wherever the data goes."""
    doc = phrase_data.__doc__
    assert "Electronic" in doc and "Dictionary Research and Development Group (EDRDG)" in doc
    assert "CC BY-SA 4.0" in doc and "https://www.edrdg.org/edrdg/licence.html" in doc
    assert f"JMdict created {phrase_data.JMDICT_CREATED}" in doc
    assert "shared under the" in doc and "same licence" in doc
